name: ESLint

on:
  push:
    branches: 
      - main

jobs:
  eslint:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        Node: [14]

    steps:
    - name: git clone
      run: git clone https://github.com/wildcat584/brain-games
    - name: npm install build
      run: npm install